### ISSUE TITLE
Conflict with Fortify Traits

### ISSUE THREAD

**Issue by a-zog** [webbingbrasil/filament-2fa#1]
Hi, thank you for this awesome plugin !

I tried to implement it along with JetStream (inertia) and I would like to know how it can play better with Fortify since it already implements ```Laravel\Fortify\TwoFactorAuthenticatable``` with conflicting traits.

Thank you in advance

**Comment by dmandrade** [comment]
This plugin is basically the same implementation of fortify so our trait has the same methods.

I believe that with the latest version you can use it together with Fortify:

1. implement `Laravel\Fortify\TwoFactorAuthenticatable` in user model
2. remove `Webbingbrasil\FilamentTwoFactorTwoFactorAuthenticatable\` from user model
3. copy method `hasEnabledFilamentTwoFactorAuthentication()` from  `Webbingbrasil\FilamentTwoFactorTwoFactorAuthenticatable\` to your user model

But I don't know if there would be any other conflict.

Let me know if works.

**Comment by a-zog** [comment]
Thank you for your help. it worked ! 🎉

Unfortunately, it conflicted with the Jetstream flow as described here #3
