### ISSUE TITLE
Login password validation being bypassed 

### ISSUE THREAD

**Issue by buffer808** [webbingbrasil/filament-2fa#2]
Trying to use this plugin for my project but seems the password is not checked and redirected directly to the 2fa page even an incorrect password is supplied.  

Fixed it by 
- creating `\App\Http\Livewire\Auth\Login` and then extending it to the plugin's `Login::class`
- change the `config/filament` to `auth.pages.login=\App\Http\Livewire\Auth\Login` 
- copy the plugin's `authenticate()` method and then
- move the `if (app(FilamentTwoFactor::class)->hasTwoFactorEnabled($user))` condition before `return` statement 

not sure if this happens on my end only, but in case, just sharing my solution

**Comment by buffer808** [comment]
Update:
- had an issue with my first workaround, reverted back the `authenticate()` method, then
- modified the `validateCredentials()` method to include the password in where clause
```
protected function validateCredentials($data)
{
    $model = Filament::auth()->getProvider()->getModel();

    $result = $model::where([
        'email' => $data['email'],
        'password'=> Hash::make($data['password'])
    ])->first();

    return tap($result, function ($user) use ($data) {
        if (! $user || ! Filament::auth()->getProvider()->validateCredentials($user, ['password' => $data['password']])) {
            $this->addError('email', __('filament::login.messages.failed'));
        }
    });
}
```

**Comment by dmandrade** [comment]
Fixed in last version

Thanks
