### ISSUE TITLE
Conflict with Jetstream 2FA flow

### ISSUE THREAD

**Issue by a-zog** [webbingbrasil/filament-2fa#3]
Thank you for your great work !
The plugin works perfectly within filament flow, unfortunately, it overrode the initial Jetstream (inertia js) 2FA flow.

The objective is to have:
A user flow:
1- Login : /login (Works)
2- 2FA validation : /two-factor-challenge (Forces redirection to /filament/two-factor-challenge)
3- Redirect to /dashboard (failed: redirects to /filament with error since user has not proper access)

An admin flow (works perfectly):
1- Login : /filament/login
2- 2FA validation : /filament/two-factor-challenge
3- Redirect to /filament

I even tried to set conditional redirection on:
```$this->app->singleton(TwoFactorLoginResponseContract::class, \App\Http\Responses\LoginResponse::class);```
But without success

Do you have any hints on how to solve this?

**Comment by dmandrade** [comment]
Ok, I think the problem here is route name collision.
So I publish a new version (v0.2.2) with another route name to prevent conflict. 
I tested it quickly on a fortify project and worked. 

Let me know if works for you

**Comment by a-zog** [comment]
It works indeed 🚀
Thank you for your reactivity
